apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-viewer-crd
  name: ml-pipeline-viewer-controller-deployment
spec:
  selector:
    matchLabels:
      app: ml-pipeline-viewer-crd
  template:
    metadata:
      labels:
        app: ml-pipeline-viewer-crd
    spec:
      containers:
      - image: gcr.io/ml-pipeline/viewer-crd-controller:0.1.15
        imagePullPolicy: Always
        name: ml-pipeline-viewer-controller
      serviceAccountName: ml-pipeline-viewer-crd-service-account