apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- namespace.yaml

namespace: foobar

patchesStrategicMerge:
- ./workflow-controller-configmap.yaml
- ./ml-pipeline-persistenceagent-deployment-patch.yaml
- ./ml-pipeline-scheduledworkflow-deployment-patch.yaml