apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- argo
- crds
- minio
- mysql
- pipeline

images:
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: v2.2.0